apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  CNFG_DB__CONNECTION__HOST: {{ include "postgresql.fullname" . }}
  RABBITMQ_HOST: otus-rabbit-rabbitmq.otus-rabbit.svc.cluster.local
  RABBITMQ_PORT: "5672"
  RABBITMQ_DEFAULT_VHOST: "/"
  BILLING_PORT: "8002"
  BILLING_HOST: otus-billing-service.otus-billing.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
  RABBITMQ_DEFAULT_USER: YXJjaA==
  RABBITMQ_DEFAULT_PASS: c3VwZXJfc2VjcmV0X3JhYmJpdA==
