apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  CNFG_DB__CONNECTION__HOST: {{ include "postgresql.fullname" . }}
---
apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
data:
  POSTGRES_DB: {{ .Values.postgresql.postgresqlDatabase | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgresql.postgresqlUsername | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.postgresqlPassword | b64enc | quote }}
