{
 "title": "Otus",
 "description": "Outs app metric dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "pod",
    "query": "label_values(kube_pod_info{namespace=\"otus-lab\",pod=~\"otus-app-.*-.{5}\"}, pod)"
   }
  ]
 },
 "panels": [
  {
   "title": "RPS Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error Rate Total Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (rate(nginx_ingress_controller_requests{status=~\"5.*\"}[1m]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Request latency Total Nginx",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(nginx_ingress_controller_request_duration_seconds_bucket[1m])))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "By methods and pods (from Application)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "repeat": "pod"
  },
  {
   "title": "RPS by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method) (rate(request_counter[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Error Rate by method",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (method)(rate(request_counter{code=~\"5.*\"}[1m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "GET",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(request_latency_bucket{method=\"GET\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(request_latency_bucket{method=\"GET\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(request_latency_bucket{method=\"GET\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(request_latency_bucket{method=\"GET\",pod=\"$pod\"}[1m])))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "POST",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(request_latency_bucket{method=\"POST\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(request_latency_bucket{method=\"POST\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(request_latency_bucket{method=\"POST\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(request_latency_bucket{method=\"POST\",pod=\"$pod\"}[1m])))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "PUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(request_latency_bucket{method=\"PUT\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(request_latency_bucket{method=\"PUT\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(request_latency_bucket{method=\"PUT\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(request_latency_bucket{method=\"PUT\",pod=\"$pod\"}[1m])))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "DELETE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by (le) (rate(request_latency_bucket{method=\"DELETE\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.5"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(request_latency_bucket{method=\"DELETE\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(request_latency_bucket{method=\"DELETE\",pod=\"$pod\"}[1m])))",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (rate(request_latency_bucket{method=\"DELETE\",pod=\"$pod\"}[1m])))",
     "legendFormat": "1"
    }
   ]
  }
 ]
}