apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
data:
  CNFG_DB__CONNECTION__HOST: otus-app-postgresql.otus-lab.svc.cluster.local
  RABBITMQ_HOST: otus-rabbit-rabbitmq.otus-rabbit.svc
  RABBITMQ_PORT: "5672"
  RABBITMQ_DEFAULT_VHOST: "/"

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
data:
  POSTGRES_DB: b3R1cw==
  POSTGRES_USER: YXJjaA==
  POSTGRES_PASSWORD: c2VjcmV0X3Bhc3N3b3Jk
  ROUNDS: MTA=
  SECRET: bXktc2VjdXJlX3NlY3JlVA==
  RABBITMQ_DEFAULT_USER: YXJjaA==
  RABBITMQ_DEFAULT_PASS: c3VwZXJfc2VjcmV0X3JhYmJpdA==