apiVersion: v1
kind: Service
metadata:
  name: {{ include "otus-billing.fullname" . }}-service
  labels:
    {{- include "otus-billing.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "otus-billing.selectorLabels" . | nindent 4 }}
